Saved signup data to mongodb + compare login input to mongodb data
software-students-fall2021/project-setup-xinhua-coherent-compfood pull request #99
Opened 2021-12-10 07:01 UTC by ErmiasMerine

2021-12-10 12:33 UTC, huang-a requested changes
Mostly looks good. Just a few changes that deal with deployment.

2021-12-10 12:33 UTC, huang-a commented on back-end/app.js
> +const cors = require('cors');
No changes needed: I think the cors import could be removed and have another header be added after L30, but this is fine as-is.

2021-12-10 12:33 UTC, huang-a commented on back-end/app.js
> +	console.log("login body", req.body)
Probably shouldn't send user credentials to stdout, this exposes passwords if logs are saved, etc.

2021-12-10 12:33 UTC, huang-a commented on front-end/src/screen/signIn.js
> +          url: 'http://localhost:61001/login',
L15: We should use the backend base url from the config to make sure this works in deployment as well.

2021-12-10 12:33 UTC, huang-a commented on front-end/src/screen/signUp.js
> +        url: 'http://localhost:61001/signup',
L19: We should use the backend base url from the config to make sure this works in deployment as well.

2021-12-12 15:43 UTC, huang-a requested changes
Oops, missed this the first time around.

2021-12-12 15:43 UTC, huang-a commented on front-end/src/screen/signIn.js
> +          url: 'http://127.0.0.1:61001/login',
L15 + another line: should be `${config.backend_base_url}` instead of `127.0.0.1:61001`

2021-12-13 03:03 UTC, ErmiasMerine commented on front-end/src/screen/signIn.js
> +            this.getBlogPost();
remains of a feature i wanted to implement but decided not to

2021-12-13 03:44 UTC, huang-a commented on front-end/src/screen/signIn.js
> +            this.getBlogPost();
ah gotcha, cool

2021-12-13 03:44 UTC, huang-a approved these changes
looks good to me

2021-12-13 03:45 UTC, merged